// Split out of EntireMenuScreen.swift (2026-09-02, Menu Feature-module
// decomposition) purely to keep that file under the 500-line new-file cap -- a
// struct's designated initializer can live in an extension in a separate file so
// long as the struct's own primary declaration defines no other explicit init.
extension EntireMenuScreen {
    public init(
        onOpenSettings: @escaping () -> Void = {},
        onClaimInterest: @escaping () -> Void = {},
        onSwitchToTalk: @escaping () -> Void = {},
        onOpenTransferHub: @escaping () -> Void = {},
        onOpenShop: @escaping () -> Void = {},
        onOpenEats: @escaping () -> Void = {},
        onOpenMarketplace: @escaping () -> Void = {},
        onOpenCommunity: @escaping () -> Void = {},
        onOpenJobs: @escaping () -> Void = {},
        onOpenProperty: @escaping () -> Void = {},
        onOpenBank: @escaping () -> Void = {},
        onOpenTransit: @escaping () -> Void = {},
        onOpenMap: @escaping () -> Void = {},
        onOpenInvest: @escaping () -> Void = {},
        onOpenWeeklySavings: @escaping () -> Void = {},
        onOpenGrow31Savings: @escaping () -> Void = {},
        onOpenYouthAccount: @escaping () -> Void = {},
        onOpenCard: @escaping () -> Void = {},
        onOpenGroupAccounts: @escaping () -> Void = {},
        onOpenIkimina: @escaping () -> Void = {},
        onOpenSacco: @escaping () -> Void = {},
        onOpenHarvestAdvance: @escaping () -> Void = {},
        onOpenVupLoan: @escaping () -> Void = {},
        onOpenStudentLoan: @escaping () -> Void = {},
        onOpenRewardsMiniApp: @escaping () -> Void = {},
        onOpenPayBillsMiniApp: @escaping () -> Void = {},
        onOpenAccountBalanceMiniApp: @escaping () -> Void = {},
        onOpenInsuranceMiniApp: @escaping () -> Void = {},
        onOpenOverview: @escaping () -> Void = {},
        onOpenSpending: @escaping () -> Void = {},
        onOpenFamilyLink: @escaping () -> Void = {},
        onOpenSubscriptions: @escaping () -> Void = {},
        onOpenCertificate: @escaping () -> Void = {},
        onOpenIdentity: @escaping () -> Void = {},
        onOpenRequestMoney: @escaping () -> Void = {},
        onOpenAutoTopUp: @escaping () -> Void = {},
        onOpenRoundUp: @escaping () -> Void = {},
        onOpenUpfrontDeposit: @escaping () -> Void = {},
        onOpenLoans: @escaping () -> Void = {},
        onOpenCreditScore: @escaping () -> Void = {},
        onOpenMotoOwnership: @escaping () -> Void = {},
        onOpenRides: @escaping () -> Void = {},
        onOpenDesignatedDriver: @escaping () -> Void = {},
        onOpenBikeRental: @escaping () -> Void = {},
        onOpenParking: @escaping () -> Void = {},
        onOpenBus: @escaping () -> Void = {},
        onOpenMotoFareCollect: @escaping () -> Void = {},
        onOpenVehicleInspection: @escaping () -> Void = {},
        onOpenVehicleValuation: @escaping () -> Void = {},
        onOpenTrustScore: @escaping () -> Void = {},
        onOpenKnowledge: @escaping () -> Void = {},
        onOpenAgentOperator: @escaping () -> Void = {},
        onOpenFloatMarketplace: @escaping () -> Void = {},
        onOpenAgentCashOut: @escaping () -> Void = {},
        onOpenForeignCurrency: @escaping () -> Void = {},
        onOpenSupport: @escaping () -> Void = {}
    ) {
        self.onOpenSettings = onOpenSettings
        self.onClaimInterest = onClaimInterest
        self.onSwitchToTalk = onSwitchToTalk
        self.onOpenTransferHub = onOpenTransferHub
        self.onOpenShop = onOpenShop
        self.onOpenEats = onOpenEats
        self.onOpenMarketplace = onOpenMarketplace
        self.onOpenCommunity = onOpenCommunity
        self.onOpenJobs = onOpenJobs
        self.onOpenProperty = onOpenProperty
        self.onOpenBank = onOpenBank
        self.onOpenTransit = onOpenTransit
        self.onOpenMap = onOpenMap
        self.onOpenInvest = onOpenInvest
        self.onOpenWeeklySavings = onOpenWeeklySavings
        self.onOpenGrow31Savings = onOpenGrow31Savings
        self.onOpenYouthAccount = onOpenYouthAccount
        self.onOpenCard = onOpenCard
        self.onOpenGroupAccounts = onOpenGroupAccounts
        self.onOpenIkimina = onOpenIkimina
        self.onOpenSacco = onOpenSacco
        self.onOpenHarvestAdvance = onOpenHarvestAdvance
        self.onOpenVupLoan = onOpenVupLoan
        self.onOpenStudentLoan = onOpenStudentLoan
        self.onOpenRewardsMiniApp = onOpenRewardsMiniApp
        self.onOpenPayBillsMiniApp = onOpenPayBillsMiniApp
        self.onOpenAccountBalanceMiniApp = onOpenAccountBalanceMiniApp
        self.onOpenInsuranceMiniApp = onOpenInsuranceMiniApp
        self.onOpenOverview = onOpenOverview
        self.onOpenSpending = onOpenSpending
        self.onOpenFamilyLink = onOpenFamilyLink
        self.onOpenSubscriptions = onOpenSubscriptions
        self.onOpenCertificate = onOpenCertificate
        self.onOpenIdentity = onOpenIdentity
        self.onOpenRequestMoney = onOpenRequestMoney
        self.onOpenAutoTopUp = onOpenAutoTopUp
        self.onOpenRoundUp = onOpenRoundUp
        self.onOpenUpfrontDeposit = onOpenUpfrontDeposit
        self.onOpenLoans = onOpenLoans
        self.onOpenCreditScore = onOpenCreditScore
        self.onOpenMotoOwnership = onOpenMotoOwnership
        self.onOpenRides = onOpenRides
        self.onOpenDesignatedDriver = onOpenDesignatedDriver
        self.onOpenBikeRental = onOpenBikeRental
        self.onOpenParking = onOpenParking
        self.onOpenBus = onOpenBus
        self.onOpenMotoFareCollect = onOpenMotoFareCollect
        self.onOpenVehicleInspection = onOpenVehicleInspection
        self.onOpenVehicleValuation = onOpenVehicleValuation
        self.onOpenTrustScore = onOpenTrustScore
        self.onOpenKnowledge = onOpenKnowledge
        self.onOpenAgentOperator = onOpenAgentOperator
        self.onOpenFloatMarketplace = onOpenFloatMarketplace
        self.onOpenAgentCashOut = onOpenAgentCashOut
        self.onOpenForeignCurrency = onOpenForeignCurrency
        self.onOpenSupport = onOpenSupport
    }
}
