expose:
  type: nodePort
  tls:
    enabled: false

persistence:
  enabled: false

trivy:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

jobservice:
  jobLoggers:
  - stdout
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

portal:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

core:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

registry:
  registry:
    resources:
      requests:
        cpu: 100m
        memory: 192Mi
      limits:
        cpu: 500m
        memory: 384Mi
  controller:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

database:
  type: internal
  internal:
    shmSizeLimit: 128Mi
    resources:
      requests:
        cpu: 100m
        memory: 192Mi
      limits:
        cpu: 300m
        memory: 384Mi

redis:
  type: internal
  internal:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi

exporter:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
