/**
 * Hand-written equivalent of granite's real auto-generated `router.gen.ts`
 * (2026-07-12, granite-adoption stage 6) -- real granite apps get this file
 * generated by the `granite` CLI scanning `pages/` (confirmed by reading a
 * real `create-granite-app` scaffold's own generated output directly).
 * Itunda's host-app runs on plain Metro, not granite's CLI/bundler, so
 * nothing generates this automatically -- but the module-augmentation
 * mechanism it relies on (TypeScript's declaration merging against
 * `RegisterScreenInput`/`RegisterScreen`, declared but not exported inside
 * `@granite-js/react-native`'s own `router/createRoute.ts`) doesn't require
 * this file to be generated, only declared correctly, which is what this
 * does by hand for pay-bills' one real route.
 *
 * DO NOT let this drift from require.context.ts's actual keys() if more
 * routes are ever added to this mini-app.
 */
import type { Route as IndexRoute } from './pages/index';
import type { Route as NotFoundRoute } from './pages/_404';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof IndexRoute)['_inputType'];
    '/_404': (typeof NotFoundRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof IndexRoute)['_outputType'];
    '/_404': (typeof NotFoundRoute)['_outputType'];
  }
}
