package rw.itunda.eats

// Real fix (2026-08-26): split out of EatsOrderService.kt once that file grew past
// its file-size-lint baseline. Pure exception declarations, no behavior -- zero-
// risk mechanical move, same package so no import changes anywhere.

class RestaurantNotFoundException(message: String) : RuntimeException(message)
class RestaurantNoAccountException(message: String) : RuntimeException(message)
class EatsBuyerNoAccountException(message: String) : RuntimeException(message)
class EmptyEatsOrderException(message: String) : RuntimeException(message)
class InvalidEatsDeliveryAddressException(message: String) : RuntimeException(message)
class InvalidEatsQuantityException(message: String) : RuntimeException(message)
class MenuItemNotFoundException(message: String) : RuntimeException(message)
class MenuItemSoldOutException(message: String) : RuntimeException(message)
class MenuItemSurplusDealExpiredException(message: String) : RuntimeException(message)
class SelfEatsOrderException(message: String) : RuntimeException(message)
class RestaurantNotAcceptingOrdersException(message: String) : RuntimeException(message)
class EatsOrderNotFoundException(message: String) : RuntimeException(message)
class InvalidEatsOrderStatusTransitionException(message: String) : RuntimeException(message)
class RiderNotAvailableException(message: String) : RuntimeException(message)
class DeliveryAlreadyClaimedException(message: String) : RuntimeException(message)
class RiderAlreadyOnDeliveryException(message: String) : RuntimeException(message)
class NotAssignedRiderException(message: String) : RuntimeException(message)
class InvalidEatsCoordinatesException(message: String) : RuntimeException(message)
class InvalidEatsDeliveryNotesException(message: String) : RuntimeException(message)
class NoActiveOfferException(message: String) : RuntimeException(message)
class MissingRequiredMenuOptionException(message: String) : RuntimeException(message)
class InvalidMenuOptionSelectionException(message: String) : RuntimeException(message)
class ScheduledOrdersNotSupportedException(message: String) : RuntimeException(message)
class InvalidScheduledOrderTimeException(message: String) : RuntimeException(message)
class MinOrderAmountNotMetException(message: String) : RuntimeException(message)
class InvalidEatsOrderChargeException(message: String) : RuntimeException(message)
class EatsOrderItemNotFoundException(message: String) : RuntimeException(message)
class EatsOrderItemAlreadyUnavailableException(message: String) : RuntimeException(message)
class EatsOrderAllItemsUnavailableException(message: String) : RuntimeException(message)
class EatsOrderNotDeliveredException(message: String) : RuntimeException(message)
class EatsOrderAlreadyTippedException(message: String) : RuntimeException(message)
class EatsOrderTipWindowExpiredException(message: String) : RuntimeException(message)
class InvalidEatsTipAmountException(message: String) : RuntimeException(message)
class EatsOrderNoRiderException(message: String) : RuntimeException(message)
