import UIKit
import React
import BrickModule
import GraniteBrownfield

/// One concrete screen per mini-app, each hardcoding its own RN component name --
/// direct iOS port of Android's `SaroniteMiniAppActivity`/`PayBillsMiniAppActivity`
/// (`android/.../miniapps/MiniAppActivity.kt`). `mainComponentName` must match the
/// `appName` each mini-app's own `app.tsx` passes to `Granite.registerApp(...)` exactly --
/// same requirement Android's own header comment documents.
class SaroniteMiniAppViewController: UIViewController, BrickModuleRegistrableViewController {
    private let mainComponentName: String
    private let miniAppScheme: String

    // The itunda-specific legacy bridge (`SaroniteBrownfieldModule.swift`, distinct from
    // granite's own generic `GraniteBrownfieldModule` TurboModule above) needs a way to
    // reach "the currently open mini-app screen" to dismiss it from `closeView()` -- same
    // role Android's `reactApplicationContext.currentActivity` plays there. A single weak
    // static is the simplest honest equivalent for "one mini-app screen open at a time,"
    // the same scope this app's granite adoption has had on every platform so far.
    static weak var current: SaroniteMiniAppViewController?

    init(mainComponentName: String, miniAppScheme: String) {
        self.mainComponentName = mainComponentName
        self.miniAppScheme = miniAppScheme
        super.init(nibName: nil, bundle: nil)
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    // Real granite native bridge -- lazy, same reasoning as Android's own lazy
    // `brickModuleRegistry`: nothing here needs to exist before this screen actually opens.
    lazy var moduleRegistry: BrickModuleRegistry = {
        let registry = BrickModuleRegistry()
        registry.register([
            GraniteBrownfieldModuleImpl(scheme: miniAppScheme) { [weak self] in
                self?.dismiss(animated: true)
            },
        ])
        return registry
    }()

    private var didAttachRootView = false

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .black
        Self.current = self
    }

    // Real, live-found gap (2026-07-16): creating the RN root view from `viewDidLoad`
    // attached a real native root view (its own default background rendered) but never
    // mounted any React content and never fired a single network call -- no crash, just
    // indefinitely inert. `viewDidLoad` runs before this view controller's view is actually
    // attached to a real `UIWindow` under a SwiftUI `.sheet` presentation; Fabric's surface
    // mounting is real-window-dependent the same way plain UIKit layout often is. Moved
    // here, guarded against re-running on a later re-appearance.
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        guard !didAttachRootView else { return }
        didAttachRootView = true

        // Ordering matters, confirmed via real diagnostics: `RCTRootViewFactory` creates its
        // `RCTHost` lazily, the *first* time a view/start call touches it.
        //
        // Real, live-found gap (2026-07-17): a bare `RCTHost.start()` left the created
        // `RCTSurfaceHostingProxyRootView` with a real, correctly-sized frame but *zero*
        // subviews forever (confirmed via a recursive-description dump at t+1s through
        // t+15s) -- the Fabric surface itself never actually attached any content view.
        // `RCTReactNativeFactory.startReactNativeWithModuleName:inWindow:` is RN's real,
        // officially-documented brownfield entry point (used even when the RN screen isn't
        // the whole app's own window) and does real additional work `RCTHost.start()` alone
        // doesn't -- switching to it here is what got a real Fabric component tree
        // (`RCTSurfaceView` → `RCTRootComponentView` → real named components) to attach at
        // all, confirmed via the same recursive-description technique.
        SaroniteHost.factory.startReactNative(withModuleName: mainComponentName, in: view.window)

        let rootView = SaroniteHost.factory.rootViewFactory.view(withModuleName: mainComponentName)
        rootView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(rootView)
        NSLayoutConstraint.activate([
            rootView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            rootView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            rootView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            rootView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
        ])

        injectBrickModuleRegistry()
    }

    /// Real granite's `BrickModule` TurboModule (`ios/.brick/BrickModule.mm`, generated by
    /// `brick-codegen`) only accepts its registry via KVC on the key `"_brickModuleRegistry"`
    /// -- confirmed by reading the generated `-setValue:forKey:` override directly, which
    /// itself carries the comment "No host attachment; app injects registry via KVC". There
    /// is no public constructor/property path, matching Android's own equivalent cast-based
    /// lookup (`reactContext.currentActivity as? BrickModuleRegistrar`) just via a different
    /// mechanism on this platform. `SaroniteBrickBridge` (a tiny ObjC helper, see its own
    /// header for why this can't be pure Swift -- `RCTHost` is invisible to the Swift Clang
    /// importer) does the actual `RCTRootViewFactory.reactHost.moduleRegistry.moduleForName:`
    /// walk via KVC. Never lets a lookup failure crash the mini-app screen -- same "don't let
    /// this kind of failure block the user" pattern as `MiniAppBundleDownloader` on Android:
    /// `getSchemeUri()`/`closeView()` simply wouldn't resolve from JS if this fails, the
    /// mini-app's actual screen still renders.
    private func injectBrickModuleRegistry() {
        guard let brickModule = SaroniteBrickBridge.brickModule(fromRootViewFactory: SaroniteHost.factory.rootViewFactory) else {
            print("⚠️ Saronite: BrickModule TurboModule instance not found -- registry injection skipped")
            return
        }
        (brickModule as AnyObject).setValue(moduleRegistry, forKey: "_brickModuleRegistry")
    }
}

/// `itunda://saronite` is this app's existing real scheme (matches Android's
/// `ItundaSaroniteHostBridge.getSchemeUri()`); each mini-app extends it with its own path
/// segment, granite's own real `getSchemePrefix` convention (`scheme://host/appName`).
final class PayBillsMiniAppViewController: SaroniteMiniAppViewController {
    init() {
        super.init(mainComponentName: "SaronitePayBills", miniAppScheme: "itunda://saronite/pay-bills")
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

/// `account-balance`/`reward-tasks`/`insurance` migrated onto the now-proven-working iOS host
/// the same way they migrated onto Android's real granite bridge (2026-07-13→14, see
/// `docs/ARCHITECTURE.md`'s mini-app host row): zero new native *logic* needed beyond a
/// concrete subclass naming its own `mainComponentName`/`miniAppScheme` -- the generic base
/// class and `SaroniteBrownfieldModule`'s full method surface (`getAccountBalance`,
/// `getRewardTasks`/`claimRewardTask`, `getInsurancePlans`/`getMyPolicies`/`enrollInsurance`)
/// were already built alongside `payBill` during the pay-bills pass, matching Android's own
/// `SaroniteBridge.kt` one-for-one.
final class AccountBalanceMiniAppViewController: SaroniteMiniAppViewController {
    init() {
        super.init(mainComponentName: "SaroniteAccountBalance", miniAppScheme: "itunda://saronite/account-balance")
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

final class RewardTasksMiniAppViewController: SaroniteMiniAppViewController {
    init() {
        super.init(mainComponentName: "SaroniteRewardTasks", miniAppScheme: "itunda://saronite/reward-tasks")
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

final class InsuranceMiniAppViewController: SaroniteMiniAppViewController {
    init() {
        super.init(mainComponentName: "SaroniteInsurance", miniAppScheme: "itunda://saronite/insurance")
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
