package rw.itunda.rideshare.web

import org.springframework.data.domain.Page
import org.springframework.data.domain.PageRequest
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.security.core.annotation.AuthenticationPrincipal
import org.springframework.web.bind.MissingRequestHeaderException
import org.springframework.web.bind.annotation.ExceptionHandler
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestHeader
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import rw.itunda.auth.RateLimitExceededException
import rw.itunda.core.domain.MotoFareTrip
import rw.itunda.core.idempotency.IdempotencyConflictException
import rw.itunda.core.idempotency.IdempotencyInProgressException
import rw.itunda.core.idempotency.IdempotencyService
import rw.itunda.core.ledger.AccountFrozenException
import rw.itunda.core.ledger.InsufficientFundsException
import rw.itunda.core.security.CurrentUser
import rw.itunda.core.web.ApiError
import rw.itunda.rideshare.MotoFareCodeNotFoundException
import rw.itunda.rideshare.MotoFareCodeNotPayableException
import rw.itunda.rideshare.MotoFareInvalidFareException
import rw.itunda.rideshare.MotoFareNoAccountException
import rw.itunda.rideshare.MotoFareSelfCollectionException
import rw.itunda.rideshare.MotoFareService
import java.math.BigDecimal

data class CollectMotoFareRequest(val code: String, val fare: BigDecimal)

// Real "tap to pay your moto-taxi fare" (2026-08-27, direct user follow-up: "now we
// can make pay for tax and moto as well") -- see MotoFareService.kt's own doc comment
// for the full sourced account. `code` is the same CustomerPaymentCode value already
// generated by POST /api/v1/merchant/pay/customer-code and shown as a QR/barcode by
// any user's own "My payment code" screen.
@RestController
@RequestMapping("/api/v1/moto-fare")
class MotoFareController(
    private val motoFareService: MotoFareService,
    private val idempotencyService: IdempotencyService,
) {
    @GetMapping("/trips")
    fun getMyTripsAsRider(
        @AuthenticationPrincipal currentUser: CurrentUser,
        @RequestParam(defaultValue = "0") page: Int,
        @RequestParam(defaultValue = "20") size: Int,
    ): ResponseEntity<Map<String, Any?>> {
        val result: Page<MotoFareTrip> = motoFareService.getMyTripsAsRider(currentUser.userId, PageRequest.of(page, size.coerceIn(1, 100)))
        return ResponseEntity.ok(mapOf("success" to true, "trips" to result.content, "totalElements" to result.totalElements, "totalPages" to result.totalPages))
    }

    @GetMapping("/earnings")
    fun getMyTripsAsDriver(
        @AuthenticationPrincipal currentUser: CurrentUser,
        @RequestParam(defaultValue = "0") page: Int,
        @RequestParam(defaultValue = "20") size: Int,
    ): ResponseEntity<Map<String, Any?>> {
        val result: Page<MotoFareTrip> = motoFareService.getMyTripsAsDriver(currentUser.userId, PageRequest.of(page, size.coerceIn(1, 100)))
        return ResponseEntity.ok(mapOf("success" to true, "trips" to result.content, "totalElements" to result.totalElements, "totalPages" to result.totalPages))
    }

    @PostMapping("/collect")
    fun collect(
        @RequestBody request: CollectMotoFareRequest,
        @RequestHeader("Idempotency-Key") idempotencyKey: String,
        @AuthenticationPrincipal currentUser: CurrentUser,
    ): ResponseEntity<Map<String, Any?>> {
        val (status, body) = idempotencyService.replayOrExecute("POST /api/v1/moto-fare/collect", idempotencyKey, request) {
            val result = motoFareService.collectFare(currentUser.userId, request.code, request.fare)
            201 to mapOf("success" to true, "collected" to result)
        }
        return ResponseEntity.status(status).body(body)
    }

    @ExceptionHandler(MotoFareCodeNotFoundException::class)
    fun handleCodeNotFound(ex: MotoFareCodeNotFoundException) = ResponseEntity.status(HttpStatus.NOT_FOUND).body(ApiError("MOTO_FARE_CODE_NOT_FOUND", ex.message ?: "Not found"))

    @ExceptionHandler(MotoFareCodeNotPayableException::class)
    fun handleCodeNotPayable(ex: MotoFareCodeNotPayableException) = ResponseEntity.status(HttpStatus.CONFLICT).body(ApiError("MOTO_FARE_CODE_NOT_PAYABLE", ex.message ?: "Conflict"))

    @ExceptionHandler(MotoFareSelfCollectionException::class)
    fun handleSelfCollection(ex: MotoFareSelfCollectionException) = ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ApiError("MOTO_FARE_SELF_COLLECTION", ex.message ?: "Bad request"))

    @ExceptionHandler(MotoFareInvalidFareException::class)
    fun handleInvalidFare(ex: MotoFareInvalidFareException) = ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ApiError("INVALID_MOTO_FARE", ex.message ?: "Bad request"))

    @ExceptionHandler(MotoFareNoAccountException::class)
    fun handleNoAccount(ex: MotoFareNoAccountException) = ResponseEntity.status(HttpStatus.NOT_FOUND).body(ApiError("MOTO_FARE_NO_ACCOUNT", ex.message ?: "Not found"))

    @ExceptionHandler(AccountFrozenException::class)
    fun handleAccountFrozen(ex: AccountFrozenException) = ResponseEntity.status(HttpStatus.CONFLICT).body(ApiError("ACCOUNT_FROZEN", ex.message ?: "Conflict"))

    @ExceptionHandler(InsufficientFundsException::class)
    fun handleInsufficientFunds(ex: InsufficientFundsException) = ResponseEntity.status(HttpStatus.CONFLICT).body(ApiError("INSUFFICIENT_FUNDS", ex.message ?: "Conflict"))

    @ExceptionHandler(RateLimitExceededException::class)
    fun handleRateLimit(ex: RateLimitExceededException) = ResponseEntity.status(HttpStatus.TOO_MANY_REQUESTS).body(ApiError("RATE_LIMITED", ex.message ?: "Too many requests"))

    @ExceptionHandler(IdempotencyConflictException::class)
    fun handleIdempotencyConflict(ex: IdempotencyConflictException) = ResponseEntity.status(HttpStatus.CONFLICT).body(ApiError("IDEMPOTENCY_KEY_CONFLICT", ex.message ?: "Conflict"))

    @ExceptionHandler(IdempotencyInProgressException::class)
    fun handleIdempotencyInProgress(ex: IdempotencyInProgressException) = ResponseEntity.status(HttpStatus.CONFLICT).body(ApiError("IDEMPOTENT_REQUEST_PROCESSING", ex.message ?: "Conflict"))

    @ExceptionHandler(MissingRequestHeaderException::class)
    fun handleMissingHeader(ex: MissingRequestHeaderException) = ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ApiError("IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key header is required"))
}
