package com.brickmodule.codegen

import run.granite.brownfield.GraniteBrownfieldModuleSpec

/**
 * Real fix for the upstream JVM signature clash in
 * `@granite-js/brownfield-module`'s vendored, generated
 * `GraniteBrownfieldModuleSpec.kt` (2026-07-12, granite-adoption stage 7) --
 * see `run/granite/brownfield/typegen/GraniteBrownfieldModuleSpec.kt` in this
 * same module for the full account of why `schemeUri` can't be a real
 * interface member.
 *
 * This extension property deliberately lives in `com.brickmodule.codegen` --
 * the exact package brick-codegen's own generated `BrickModuleImpl.kt` is
 * declared in (`android/.brick/src/main/kotlin/BrickModuleImpl.kt`, confirmed
 * by reading it directly), not in `run.granite.brownfield` alongside the
 * interface itself. Kotlin resolves same-package members without an explicit
 * import, including across module/compile-classpath boundaries as long as
 * the package name matches -- and `BrickModuleImpl.kt` is a generated file
 * itunda can't add an import statement to (it's regenerated by
 * `brick-codegen` at build time, per `brick_modules.gradle`'s own
 * `needsCodegen` check). Its real call site
 * (`return typedModule.schemeUri`, confirmed by reading the generated file)
 * needs this to resolve with zero import required, which same-package
 * placement provides.
 */
val GraniteBrownfieldModuleSpec.schemeUri: String
    get() = getSchemeUri()
