export const theLanguageWeNeverAskedAbout = {
  slug: 'the-language-we-never-asked-about',
  title: "We built a financial-inclusion app for Rwanda and never once asked whether it spoke Kinyarwanda",
  date: '2026-08-08',
  author: 'Web, Android & iOS Teams',
  tags: ['web', 'android', 'ios', 'i18n', 'accessibility', 'research', 'incident-writeup'],
  excerpt:
    "A research pass into how Paytm and PhonePe serve low-digital-literacy users in India turned into a much simpler, much more uncomfortable question about our own app: does it work in the language most of our own users actually speak? We checked. It didn't. Here's the honest first step, not the finished answer — including a real bug the compiler never would have caught.",
  content: `
This app exists because of a real mission statement, repeated enough times in our own commit history and design docs that it stopped feeling like something we needed to double-check: financial inclusion, for people the traditional banking system in Rwanda has historically underserved. We've built real infrastructure around that idea — alternative credit scoring that doesn't need a credit bureau, a USSD channel for feature phones, an agent network for cash-in/cash-out where there's no bank branch. What we never did, in any of that work, was ask a much more basic question: what language is all of this actually written in?

The answer, once we finally checked, was uncomfortable in its simplicity. English. All of it. Every screen, every button, every error message, on every platform.

## How the question even came up

We'd been researching Paytm and PhonePe — two real fintech products serving hundreds of millions of users in a market with a lot in common with ours: large populations with limited traditional banking access, a wide range of digital literacy, and a real, measured preference among new fintech users for their own language over English — over half, in the specific market we were looking at. That's not a soft cultural note. Language is UX. A financial app that reads like a foreign document to someone is an app that's harder to trust with money, no matter how good the underlying product is.

That sent us checking something about our own app we'd genuinely never checked before: does it support Kinyarwanda anywhere at all?

## What we actually found

Nothing. Not partially, not on one platform with gaps elsewhere — we checked every convention we could think of, across web, Android, and iOS: locale-specific resource folders, an i18n directory, a localization config, a stray translation key anywhere in the codebase. All empty. Every one of the three real client platforms we ship hardcodes English directly into the UI. Not a placeholder, not a TODO — just English, everywhere, because nobody had ever built anything else.

## What we shipped, and what we very deliberately didn't

Full localization of three separate client codebases is not a today problem. It's probably not a this-week problem. Realistically it's a project of its own — locale infrastructure on three different platforms, and then the actual work of translating what's likely thousands of individual strings, correctly, in a language none of us on this particular pass are fluent native speakers of. Pretending otherwise and rushing something across all three platforms in one sitting would have produced exactly the kind of half-finished, silently-declared-done work we've tried hard not to ship this whole project.

So we did the smaller, honest version instead. Real locale infrastructure went into the web app — a small dictionary-based system, deliberately not a heavyweight i18n framework, because right now we have two languages and one translated screen, not the dozens of locales and plural-rule tables a bigger framework is built for. A working language switcher landed on the one screen that matters most before anything else does: login. It remembers your choice. It defaults to Kinyarwanda automatically if that's what your phone is already set to.

And then we said, directly in the code, the thing that matters most about what we just built: the Kinyarwanda text is a careful, good-faith translation, not verified by a native speaker. That's not a hedge to cover ourselves — it's the same honesty this codebase already insists on everywhere else it can't fully verify something itself. A demo balance gets labeled as a demo balance. A simulated ID check gets labeled as simulated. This gets the same treatment: real infrastructure, real working feature, translation quality flagged honestly rather than asserted with confidence we don't actually have.

## The switcher that said "EN" twice in a row

We didn't stop at web. Android's own login screen is the same kind of highest-traffic, first-impression screen, and it had the identical problem: not one string resource anywhere in the whole app module, everything hardcoded straight into Kotlin. We pulled every literal string out into real \`values/strings.xml\` and \`values-rw/strings.xml\` resources, wired a language switcher into the same top bar, wrote it against Android's standard per-app language API, watched it compile clean, and moved on to verify it — which is where it stopped being clean.

We built the debug APK, installed it on a real emulator, and tapped the switcher. It still said "EN." We checked whether we'd tapped the wrong spot — pulled the exact on-screen coordinates straight from the UI hierarchy, tapped dead center, twice. Still "EN." That's the moment a change stops being "probably fine, it compiled" and starts being a real bug, and it's exactly the kind of thing that only shows up when you actually run the thing instead of trusting the build log.

The real cause: the API we used, \`AppCompatDelegate.setApplicationLocales\`, only works if the screen belongs to an \`AppCompatActivity\`. Ours doesn't — it's a plain \`FragmentActivity\`, which means there's no \`AppCompatDelegate\` attached to it to even notice the language had changed, let alone act on it. The call wasn't throwing an error. It was just talking to nobody.

Switching the app's whole Activity base class to fix one language switcher would have been a much bigger, riskier change than the feature itself. Instead we built the switch ourselves: wrap the localized screen in its own configuration override, applied directly through Compose, independent of whatever kind of Activity happens to be hosting it. Rebuilt, reinstalled, tapped the switcher again. This time the screen actually changed — English to Kinyarwanda, live, no reload. We killed the app entirely and relaunched it to check the choice actually stuck. It did.

## The third platform, and the honest gap in how we checked it

We closed out the third platform the same day. iOS's login screen got the identical treatment — a small dictionary of strings, a toggle switcher, a choice that survives closing and reopening the app. We deliberately kept it inside the one file that already existed rather than adding a new file to the project: this particular Xcode project doesn't use the newer auto-syncing folder feature, which means every new file has to be registered by hand in a large, easy-to-corrupt project file. That felt like a bad trade for a single screen's worth of strings, so we didn't make it.

Here's the part worth being honest about instead of quietly smoothing over: we couldn't check this one the way we checked Android's. The Android bug only surfaced because we installed a real build on a real emulator and pressed the actual button. We don't have that same setup ready for iOS in this environment — the full app can't even finish linking yet, for reasons that have nothing to do with this change, and there's no simulator-screenshot habit built up the way there is on the Android side. What we do have is a clean build of the specific file with zero errors, a clean syntax check, and a clean accessibility pass. That's real signal, but it's not the same thing as watching the screen actually change languages in front of us, and after what just happened on Android, we're not willing to pretend those are equivalent. Said plainly, in the code and here: this one still needs a real device check before anyone treats it as verified the same way the other two are.

## The second screen, and the sentence that doesn't translate word-for-word

Login was always going to be the easy case: short labels, no dynamic data. The next real screen on our own roadmap — wallet overview, the one every user actually lands on right after logging in — wasn't. "Savings: 120,000 RWF across 3 goals" has a number and a count sitting inside an otherwise-fixed sentence, and the lazy way to localize that is to just glue the English sentence structure together with different words dropped in. That works passably for one language pair and breaks the moment you add a language whose word order doesn't match — which is exactly why a real localization system uses named placeholders instead: a template with \`{{amount}}\` and \`{{count}}\` sitting wherever they belong in that language's own sentence, not wherever English happens to put them.

We added that — real interpolation support in the same small dictionary system, not a rewrite — and used it for every dynamic string on the overview screen: savings, loans, investments, insurance, a linked account's demo balance. We couldn't get a real logged-in screenshot of this one the way we did for login; it needs an actual signed-in session pulling real account data, and this environment's dev server has no backend behind it to serve that. So this one is verified a different way: the type-checker validated the whole component tree, and we checked the interpolation function itself against real inputs by hand — six cases, including what happens when a parameter is missing — and then went through every single call site and confirmed its parameter names actually matched what its own template expected, since that's exactly the kind of quiet mismatch a generic type system won't catch for you. Real verification, just not the same kind as before, and said that way rather than blurred together with it.

## Porting the same screen to Android found a bug in yesterday's work

We took the overview screen to Android next, using the platform's own real string-resource system instead of hand-rolling another dictionary. Same strings, same dynamic amounts, Android's own native format-specifier syntax standing in for the placeholders we'd built by hand on web. Straightforward porting work, until it wasn't: going through every message the screen could show, we found one — the exact same "this account couldn't be verified" message from the earlier account-linking bug writeup — that had never made it into web's own translation file at all. It was still sitting there in English, hardcoded, inside the very file we'd already gone through once to localize everything else. We fixed it in two places at once: added the missing key to Android's strings, and went back and added the same key to web's translation file, so the gap didn't end up living on one platform and not the other.

That's worth sitting with for a second. We built a whole localization pass over this screen, checked every call site's parameters by hand, ran a real type-checker over the result — and still missed one string, because the checking we did was thorough within the screen's happy path and this one only shows up on a specific error condition. The fix wasn't clever. It was going through the same screen a second time, from a different starting point, and simply looking harder.

The Kotlin compiler caught something else while we were in there, unrelated to any of this: a property read from a different module wouldn't smart-cast the way the exact same code shape does when everything lives in one file, a real, narrow rule about how Kotlin reasons across module boundaries that most people only learn about by hitting it. Small, unglamorous, exactly the kind of thing a strict compiler is for.

## The screenshot we didn't get, and why we stopped asking for it

We wanted the same proof on Android that we got for its login screen: a real emulator, a real tap, a real result on screen. We got partway there — logged all the way into a real account on a real running backend, on this exact build, watched the actual wallet balance render. Then, navigating toward the overview screen itself, the emulator just stopped responding. Not slow — stuck. We waited two full minutes past a normal timeout before accepting that this wasn't going to resolve on its own; the most likely explanation is a heavier virtual machine also running on this same machine competing for the same resources.

We could have kept retrying. We didn't. An environment that's already straining under load is not the moment to lean on it harder for one more screenshot, and the honest thing to do instead was stop, write down exactly what got verified and what didn't, and move on. So: this screen compiles cleanly, passes every static check we have, and its login-adjacent code path was proven live minutes earlier on this same build. Its own render, in its own language, on an actual screen — not this time. Both of those sentences are true, and only writing down the first one would have been a quieter kind of dishonest.

## Closing the grid, and not making the same mistake twice

iOS got the same second screen the same day, which meant every platform we ship now has both of our two localized screens. This time we knew to look for the string we'd missed the first time around — it went into iOS's version from the very start, not as a second pass. We also didn't duplicate the small piece of logic that decides which language to show first; it already existed from the login screen, living in a different file, so we just made it visible to the file that needed it too, instead of writing a second copy that could quietly drift from the first one over time.

No emulator fight this round — iOS never had a live-device screenshot to lose in the first place, so the honest bar for this platform was already lower than Android's, and it stayed exactly where it was: clean build, clean checks, no live render. Six corners of a two-screen, three-platform grid now exist. None of them have been looked at by someone who actually speaks the language we're claiming to support.

## The screen that actually matters most, verified for real this time

Everything so far had a real, honest asterisk on it somewhere — a screenshot we couldn't get, a backend session we couldn't simulate, a build we could only trust the compiler on. The third screen we localized is the one where none of that was acceptable, because it's the one screen in this whole app where getting something wrong costs someone real money: sending it. So before writing a single line, we made sure we could actually watch it work, not just compile.

We didn't have a browser-automation library sitting around for this. What we did have was a real login endpoint, a real token it hands back, and the fact that a real browser will happily talk to itself over its own remote-debugging protocol if you ask it directly. So we logged in for real over curl, took the real token back, and wrote about a hundred lines of plain JavaScript that opens a raw connection to that protocol, drops the token into the browser's own storage the same way the app's login flow would, and then does the same thing a person does: click the button, watch what changes, take a picture.

It found one real, small thing immediately — the button that actually opens the transfer screen lives in a different component than the screen itself, and we'd translated the screen without touching its own front door. Same shape of gap as the missing string from last time, just architectural instead of textual. Fixed in the same pass, not a separate one.

Then it worked. All the way through — the form, a real saved contact, a real amount, the confirmation screen with that contact's real phone number and that real amount both correctly slotted into a Kinyarwanda sentence in the right place, not force-fit into English word order. We watched it happen. Sent the actual pictures. This is the best-verified piece of work in this entire effort, on the one screen where "best-verified" was never optional.

One thing surfaced in that same screenshot that we're leaving exactly as visible as it looked: a "report this as a scam" link on the confirmation screen, sitting there in English while everything around it speaks Kinyarwanda. It's a different component we didn't touch this pass. We're not fixing it quietly in an edit nobody sees — it's in the screenshot we're showing you, and it's written down here.

## The same screen, on the platform that builds it differently

Android's version of this same flow turned out to be a genuinely different piece of software, not a port. Where web asks for a recipient and an amount on one form, Android's version is a real two-step wizard built against actual reference screenshots — pick a recipient, then a separate full screen just for the amount, complete with quick-amount chips and its own device-verification dialog for a new phone. The module that owns this screen had never had a single string resource file in it. We built one from nothing.

Reading through it closely to find every string turned up something that had nothing to do with translation. The file's own header comment still described itself as "a UI shell, not wired to the backend" — an honest, accurate thing to write at some earlier point, and false for a while now. The flow it's attached to calls the real transfer endpoint, gates on real device verification, requires a real biometric confirmation. Nobody had gone back to update the comment once the wiring became real. We fixed the comment in the same pass as the translation, not because it was in scope, but because leaving a confidently-wrong sentence at the top of a file is its own kind of bug.

We can't show you a screenshot of this one working. The emulator that would have given us that proof is the same one that failed earlier today, and we're treating that as closed for this session rather than fighting it again. What we have instead is a clean compile of the module and a clean accessibility pass — real signal, the same tier iOS's screens have gotten, and we're saying so plainly rather than letting three different verification tiers blur into one "it's done."

## The last platform, and the module that couldn't just copy the pattern

iOS was the last cell left in the grid, and it looked at first like it should be the easy one — we'd already done this exact screen twice. It wasn't. The two screens that make up this flow don't live in the same part of the app as the login screen we'd already localized; they live in a separate module that this codebase deliberately keeps from depending back on the part of the app that owns the language switcher. The same boundary that made Android build a second, independent set of translated strings for its own equivalent module showed up again here, in a completely different language and a completely different dependency system, for the same underlying reason: a screen that can't see the switcher can't ask it what language to speak, so it has to carry its own small answer to that question. We gave it one — a tiny, self-contained dictionary, reading the same saved preference everyone else already writes to, so a person who picks Kinyarwanda once gets it everywhere without either half of the app needing to know the other exists.

Two smaller pieces of this same flow live back in the part of the app that does share the switcher directly, and we didn't leave them out just because the interesting problem was elsewhere. One is the device-verification dialog — the "we don't recognize this phone, type your password again" prompt. It turns out that same dialog is reused by four other flows entirely: sending a gift, checking out in the marketplace, checking out on the food-delivery side, buying or selling a stock. Translating it here means all five got it, not just this one — the kind of shared-component payoff that only shows up when you actually go looking at what else calls the thing you're touching, instead of assuming a screen's dependencies stop at what you can see in the file you opened.

The other piece was a real echo of a gap from two screens ago. This same transfer flow has a second, separate "report this number as a scam" moment — not the link we found and left honestly untranslated last time, but a whole small form that asks why you're reporting someone, on both platforms. Localizing iOS's version of it meant reading it closely enough to notice Android had the identical form, sitting in a completely different file than the one we translated last time, still speaking only English. We didn't leave that for a future pass. We fixed both in the same sitting, on the theory that finding a gap on one platform and not immediately checking whether the sibling platform has the same one is just deferring work we already know needs doing.

## The screen we assumed we'd already finished

Adding a fourth screen meant asking a question we'd been answering by assumption: which screen does a person actually land on first? We'd been calling the account-overview screen "the second screen," the one right after login — and it genuinely is a real, separate screen, fully translated. It just isn't the one the app actually opens to. That's a different screen entirely, a simpler wallet-balance-and-quick-actions view, and it had only ever been half finished: the balance card and the money-sending flow it opens were done, because those were the pieces that mattered for the transfer work. Everything else on that same screen — the error message shown when it fails to load, two small quick-action buttons, a device-verification prompt that's this platform's own version of a dialog we'd already translated twice elsewhere, and a "report this as a scam" link we'd explicitly flagged and left alone two passes ago — was still sitting in English on the actual first thing a signed-in user sees.

We finished those four pieces, not the whole screen — there's a longer list below the balance card, transaction history and a handful of cards, that's still English and staying that way for now, named plainly rather than quietly implied to be done. But the part we did finish, we finished the way we finished the transfer flow: with a real browser, a real login, and real Kinyarwanda showing up in a real running page, not just a compiler agreeing the code was well-formed. We watched the two quick-action buttons render in Kinyarwanda. We clicked through an actual saved contact, submitted an actual amount, and watched the scam-report link on the real confirmation screen come back in the language we'd set it to. Small thing, real proof.

## What's still true after today

Every screen this thread set out to localize — login, the account overview, and the transfer flow — now exists in both languages on all three platforms. Nine cells, all filled. That is not the same thing as nine cells done well, and the gap between those two sentences is the honest part of this post. Two of the nine now — web's transfer flow, and the small slice of web's real landing screen fixed today — have been watched actually working, end to end, by a real browser driven against a real logged-in session. Everything else stands on a compiler and a linter agreeing the code is well-formed, which is real signal and also nowhere near the same claim. Nobody who speaks Kinyarwanda as a first language has read a single one of these strings yet. None of that changed today, and none of it should get quietly rounded up to "done" because the grid finally looks complete on paper. A mission statement about financial inclusion is a real commitment, not a decoration, and the honest state of it right now is: present everywhere, verified unevenly, still waiting on the one kind of review that actually matters for language — someone who was raised speaking it telling us where we got it wrong. The pattern underneath every gap we found along the way — the silent switcher, the missing string, the missing front door, the stale comment, the untranslated form sitting in a sibling file nobody thought to check, the screen we assumed was finished because we'd finished a different screen next to it — was always the same one: a pass that feels thorough can still miss something, and the only way to find out is to go back and look again, on purpose, assuming there's more rather than assuming there isn't.
`,
};
