name: Itunda Android Lab Development

jobs:
  build_android:
    name: Build Android Development
    type: build
    environment: development
    params:
      platform: android
      profile: development
